export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_CONFLICT = 409

export const STATUS_CODE_INVALID = 400
export const STATUS_CODE_UNAUTHORIZED = 401
