export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_NO_CONTENT = 204

export const STATUS_CODE_INVALID = 400
export const STATUS_CODE_UNAUTHORIZED = 401
export const STATUS_CODE_FORBIDDEN = 403
export const STATUS_CODE_CONFLICT = 409

export const STATUS_CODE_INTERAL_ERROR = 500
